[package]
name = "markdown-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# A cross-platform GUI library inspired by Elm
iced = "0.6.0"

